forum_core_default_admin:
    path: /admin
    defaults: { _controller: CoreBundle:Default:admin }

forum_core_security_login:
    path: /login
    defaults: { _controller: CoreBundle:Security:login }
    options:
        expose: true

forum_core_security_login_check:
    path: /login_check
    defaults: { _controller: CoreBundle:Security:loginCheck }
    options:
        expose: true

forum_core_security_logout:
    path: /logout
    options:
        expose: true

forum_core_default_index:
    path: /
    defaults: { _controller: CoreBundle:Default:index }

forum_core_default_homepage:
    path: /forum/{forumSlug}
    defaults: { _controller: CoreBundle:Default:homepage, forumSlug: null }

forum_core_category_category:
    path: /category/{categorySlug}
    defaults: { _controller: CoreBundle:Category:category, categorySlug: null }

forum_core_subcategory_subcategory:
    path: /subcategory/{subcategorySlug}/{sortBy}/{page}
    defaults: { _controller: CoreBundle:Subcategory:subcategory, subcategorySlug: null, sortBy: dateUpdated, page: null }

forum_core_topic_topic:
    path: /topic/{topicSlug}/{page}
    defaults: { _controller: CoreBundle:Topic:topic, topicSlug: null, page: null }

forum_core_topic_post_message:
    path: /topic/{topicSlug}/postMessage/postMessage/{messageId}
    defaults: { _controller: CoreBundle:Topic:postMessage, topicSlug: null, messageId: null }

forum_core_topic_delete_message:
    path: /topic/delete/delete/{messageId}
    defaults: { _controller: CoreBundle:Topic:deleteMessage }
    options:
        expose: true

forum_core_topic_move_message:
    path: /topic/move/move/{messageId}
    defaults: { _controller: CoreBundle:Topic:moveMessage }
    options:
        expose: true

forum_core_register_send_mail:
    path: /register/sendMail
    defaults: { _controller: CoreBundle:Register:sendMail }

forum_core_register_index:
    path: /register
    defaults: { _controller: CoreBundle:Register:index }
    options:
        expose: true

forum_core_register_register_account:
    path: /register/registerAccount
    defaults: { _controller: CoreBundle:Register:registerAccount }

forum_core_register_check_for:
    path: /register/checkFor
    defaults: { _controller: CoreBundle:Register:checkFor }
    options:
        expose: true

forum_core_profile_page_profile_page:
    path: /profilePage/{username}
    defaults: { _controller: CoreBundle:ProfilePage:profilePage, username: null }
    options:
        expose: true

forum_core_profile_page_change_or_remove_avatar:
    path: /changeAvatar/{username}
    defaults: { _controller: CoreBundle:ProfilePage:changeOrRemoveAvatar, username: null }
    options:
        expose: true

forum_core_profile_page_change_password:
    path: /changePassword/{username}
    defaults: { _controller: CoreBundle:ProfilePage:changePassword, username: null }

forum_core_notification_check_for_new_notifications:
    path: /checkForNewNotifications/{userId}
    defaults: { _controller: CoreBundle:Notification:checkForNewNotifications, userId: null }
    options:
        expose: true

forum_core_conversation_show_conversations:
    path: /privateMessaging/show/{conversationSlug}
    defaults: { _controller: CoreBundle:Conversation:showConversations, conversationSlug: null }
    options:
        expose: true

forum_core_conversation_send_new_private_message:
    path: /privateMessaging/sendNewPrivateMessage
    defaults: { _controller: CoreBundle:Conversation:sendNewPrivateMessage }
    options:
        expose: true

forum_core_conversation_reply_to_conversation:
    path: /privateMessaging/replyToConversation/{conversationSlug}
    defaults: { _controller: CoreBundle:Conversation:replyToConversation, conversationSlug: null }
    options:
        expose: true

forum_core_search_search_results:
    path: /searchResults/{page}
    defaults: { _controller: CoreBundle:Search:searchResults, page: 1 }
    options:
        expose: true

forum_core_user_show:
    path: /user/show/{page}/{like}
    defaults: { _controller: CoreBundle:User:show, page: 1, like: null }
    options:
        expose: true