forum_core_default_index:
    path: /
    defaults: { _controller: CoreBundle:Default:index }

forum_core_default_homepage:
    path: /forum/{forumSlug}
    defaults: { _controller: CoreBundle:Default:homepage, forumSlug: null }

forum_core_category_category:
    path: /category/{categorySlug}
    defaults: { _controller: CoreBundle:Category:category, categorySlug: null }

forum_core_subcategory_subcategory:
    path: /subcategory/{subcategorySlug}
    defaults: { _controller: CoreBundle:Subcategory:subcategory, subcategorySlug: null }

forum_core_topic_topic:
    path: /topic/{topicSlug}
    defaults: { _controller: CoreBundle:Topic:topic, topicSlug: null }

forum_core_topic_post_message:
    path: /topic/{topicSlug}/postMessage/{messageId}
    defaults: { _controller: CoreBundle:Topic:postMessage, topicSlug: null, messageId: null }

forum_core_topic_delete_message:
    path: /topic/delete/{messageId}
    defaults: { _controller: CoreBundle:Topic:deleteMessage }

forum_core_register_send_mail:
    path: /register/sendMail
    defaults: { _controller: CoreBundle:Register:sendMail }

forum_core_register_index:
    path: /register
    defaults: { _controller: CoreBundle:Register:index }

forum_core_register_register_account:
    path: /register/registerAccount
    defaults: { _controller: CoreBundle:Register:registerAccount }


forum_core_default_admin:
    path: /admin
    defaults: { _controller: CoreBundle:Default:admin }

forum_core_security_login:
    path: /login
    defaults: { _controller: CoreBundle:Security:login }

forum_core_security_login_check:
    path: /login_check
    defaults: { _controller: CoreBundle:Security:loginCheck }

forum_core_security_logout:
    path: /logout
