# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Forum\CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 4

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMINISTRATOR: ROLE_MODERATOR

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory:
#                users:
#                    alin:  { password: alin, roles: [ 'ROLE_ADMIN' ] }
        our_db_provider:
            entity:
                class: CoreBundle:User
                property: username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: forum.security.authentication_handler
                failure_handler: forum.security.authentication_handler
            logout:
#                success_handler: forum.security.logout_success_handler
                path: /logout
                target: /
            provider: our_db_provider
            remember_me:
                key: %secret%
                lifetime: 604800 # 1 week

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/admin, roles: ROLE_ADMIN }