<?php

namespace Forum\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Forum\CoreBundle\Entity\Message;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * Find latest
     *
     * @param array $topicId
     *
     * @return Message
     */
    public function findLatest($topicId)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.topic = (:topicId)')
            ->setParameter('topicId', $topicId)
            ->orderBy('m.dateUpdated', 'desc')
            ->setMaxResults(1);
        $result = $qb->getQuery()->getResult();

        if (count($result) != 0) {
            return $result[0];
        } else {
            return $result;
        }
    }
}
