<?php

namespace Forum\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrivateMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateMessageRepository extends EntityRepository
{
}